//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisador_Log_Negocio.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_GAMEEntities : DbContext
    {
        public BD_GAMEEntities()
            : base("name=BD_GAMEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game_BD> Game_BD { get; set; }
        public virtual DbSet<Morte_BD> Morte_BD { get; set; }
        public virtual DbSet<Player_BD> Player_BD { get; set; }
    }
}
